### PR TITLE
Move to static scraper API

### PR DESCRIPTION
**Pull request by qasim**
Lot's of code change here, have a look and test it out if you can. Will change README.md to reflect the changes as well.
#14

### CODE REVIEW

**Comment by kashav** [comment]
Just got the chance to test this – seems like `CourseFinder` is broken. Scrapes 4 courses then stops at `ACMD02H3Y20165`.

**Comment by kashav** [comment]
Ah I think I found it – forgot to change [this](https://github.com/cobalt-uoft/uoft-scrapers/blob/master/uoftscrapers/scrapers/coursefinder/__init__.py#L47) back!

**Comment by qasim** [comment]
@kshvmdn woooooooooooooooops

**Comment by qasim** [comment]
Fixed in [0.3.1](https://pypi.python.org/pypi/uoftscrapers/0.3.1)

#movefastandbreakthings

**Pull request merged**
